paper: Add check for Minecraft version
Will print an easy-to-understand error message on startup instead of waiting until we run into a NoSuchMethodError or similar